### ISSUE TITLE
Use ansible facts to discover the architecture

### ISSUE THREAD

**Issue by 9seconds** [rlex/ansible-role-mtg#1]
Thanks a lot for this role!

Currently, this playbook hardcodes [amd64 architecture](https://github.com/rlex/ansible-role-mtg/blob/master/tasks/install.yml#L24). Is it possible to use `ansible_architecture` fact to identify binary to use? For example, Scaleway runs ARM machines so it is possible that mtg is gonna be launched on other architectures.

**Comment by rlex** [comment]
It's possible, however there is two issues: 
1) checksum validation will fail with default parameters (unless i pre-generate every checksum)
2) ansible_architecture reports "x86_64" instead of "amd64".

**Comment by rlex** [comment]
Kind of fixed in https://github.com/rlex/ansible-role-mtg/commit/4bcd856f89b00ae731715cb87fc2e20b34b02626
